// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHGH1p5XNGK0QMPDIrTH6gsQn6qkTIBnA',
    appId: '1:659420044043:web:0dd18a14c484e44b6a200e',
    messagingSenderId: '659420044043',
    projectId: 'exampleflutterapp-3cd10',
    authDomain: 'exampleflutterapp-3cd10.firebaseapp.com',
    storageBucket: 'exampleflutterapp-3cd10.appspot.com',
    measurementId: 'G-2NK0PRN612',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqlYeYND2hbaCu-nwiMkEqScozNZp8Ehw',
    appId: '1:659420044043:android:615154bb60eafe216a200e',
    messagingSenderId: '659420044043',
    projectId: 'exampleflutterapp-3cd10',
    storageBucket: 'exampleflutterapp-3cd10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEeJBavZ00PrvbRf3MacZWgM9McWo5C2Q',
    appId: '1:659420044043:ios:47b4d432e263ad666a200e',
    messagingSenderId: '659420044043',
    projectId: 'exampleflutterapp-3cd10',
    storageBucket: 'exampleflutterapp-3cd10.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEeJBavZ00PrvbRf3MacZWgM9McWo5C2Q',
    appId: '1:659420044043:ios:69a56d32e018c9ef6a200e',
    messagingSenderId: '659420044043',
    projectId: 'exampleflutterapp-3cd10',
    storageBucket: 'exampleflutterapp-3cd10.appspot.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
